import { prisma } from "../../lib/prisma";

export class LobbyRepository {
  
  // The Genesis Action
  async createLobby() {
    return await prisma.lobby.create({
      data: {
        // ID and UUID are auto-generated by Prisma [cite: 56]
        turn_counter: 0, // [cite: 130]
        world_bible: [], // Enforced as an empty array [] to support String[][] [cite: 130]
      }
    });
  }

  async addParticipant(userId: string, lobbyId: string) {
    const lobby = await prisma.lobby.findUnique({
      where: { lobby_id: lobbyId },
      select: { users: true }
    });
    lobby?.users.push(userId);
    await prisma.lobby.update({
      where: { lobby_id: lobbyId },
      data: {
        users: lobby?.users || []
      }
    });
  }

  // The Read Action (For the UI Waiting Room)
  async getLobbyWithParticipants(lobbyId: string) {
    return await prisma.lobby.findUnique({
      where: { lobby_id: lobbyId },
      include: {
        // Fetch the characters currently linked to this lobby
        characters: {
          select: {
            character_id: true,
            name: true,
            is_ghosted: true // [cite: 59]
          }
        },
        turn_ledgers: true
      }
    });
  }
}